import React from 'react';
import { 
  Building, 
  Target, 
  Rocket, 
  DollarSign, 
  Users, 
  CheckCircle, 
  AlertCircle,
  TrendingUp,
  Shield,
  Cpu
} from 'lucide-react';
import { buildBusinessPlanDocument } from '../utils/exportHelpers';

/**
 * BusinessPlanPrintView
 * 
 * Rendered inside DashboardPage with className="print-only"
 * (or used directly). On screen it is completely invisible.
 * When the user prints (or saves to PDF), it formats into a
 * clean, professional A4/portrait executive business plan document.
 */
const BusinessPlanPrintView = ({ data }) => {
  const doc = buildBusinessPlanDocument(data);
  const { metadata, executiveSummary, companyOverview, marketAndPersonas, leanCanvas, mvpRoadmap, revenueModel, competitors, nextSteps } = doc;

  const leanCanvasKeys = [
    { key: 'problem', label: '1. Problem' },
    { key: 'solution', label: '2. Solution' },
    { key: 'uniqueValueProposition', label: '3. Unique Value Proposition' },
    { key: 'unfairAdvantage', label: '4. Unfair Advantage' },
    { key: 'customerSegments', label: '5. Customer Segments' },
    { key: 'keyMetrics', label: '6. Key Metrics' },
    { key: 'channels', label: '7. Channels' },
    { key: 'costStructure', label: '8. Cost Structure' },
    { key: 'revenueStreams', label: '9. Revenue Streams' }
  ];

  return (
    <div id="business-plan-printable" className="print-only print-business-plan-container">
      {/* 1. COVER PAGE */}
      <div className="print-bp-cover">
        <div className="mb-6">
          <span className="px-4 py-1.5 rounded-full text-xs font-semibold tracking-wider uppercase bg-indigo-50 text-indigo-700 border border-indigo-200">
            {metadata.industry} • Executive Business Plan
          </span>
        </div>
        <h1 className="text-5xl font-extrabold text-gray-900 mb-4 tracking-tight">
          {metadata.startupName}
        </h1>
        <p className="text-xl text-indigo-600 font-medium mb-12 max-w-xl mx-auto">
          {companyOverview.usp || 'Strategic Roadmap & Business Execution Plan'}
        </p>

        <div className="p-6 bg-gray-50 border border-gray-200 rounded-2xl max-w-2xl mx-auto text-left mb-16">
          <p className="text-xs uppercase tracking-wider text-gray-400 font-semibold mb-2">Elevator Pitch</p>
          <p className="text-base text-gray-700 italic leading-relaxed">
            "{executiveSummary.elevatorPitch}"
          </p>
        </div>

        <div className="text-xs text-gray-400 space-y-1">
          <p>Generated by Startup-AI on {metadata.generatedDate}</p>
          <p>Confidential & Proprietary • Prepared for Founders and Investors</p>
        </div>
      </div>

      {/* 2. EXECUTIVE SUMMARY & OVERVIEW */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <Building className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">1. Executive Summary & Overview</h2>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-4">
          <div className="print-bp-card">
            <div className="flex items-center space-x-2 mb-2 text-red-600">
              <AlertCircle className="w-4 h-4" />
              <h3 className="font-semibold text-sm">Problem Statement</h3>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed">
              {companyOverview.problem}
            </p>
          </div>

          <div className="print-bp-card">
            <div className="flex items-center space-x-2 mb-2 text-green-600">
              <CheckCircle className="w-4 h-4" />
              <h3 className="font-semibold text-sm">Proposed Solution</h3>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed">
              {companyOverview.solution}
            </p>
          </div>
        </div>

        <div className="print-bp-card">
          <p className="text-xs font-semibold text-indigo-600 uppercase mb-1">Unique Value Proposition</p>
          <p className="text-sm font-medium text-gray-800">{companyOverview.usp}</p>
        </div>
      </div>

      {/* 3. TARGET MARKET & USER PERSONAS */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <Users className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">2. Target Market & User Personas</h2>
          </div>
        </div>

        <div className="print-bp-card mb-4">
          <p className="text-xs font-semibold text-gray-500 uppercase mb-1">Primary Target Audience</p>
          <p className="text-sm text-gray-800">{marketAndPersonas.targetAudience}</p>
        </div>

        {marketAndPersonas.personas.length > 0 && (
          <div className="grid grid-cols-2 gap-4">
            {marketAndPersonas.personas.map((persona, index) => (
              <div key={index} className="print-bp-card">
                <div className="flex justify-between items-start mb-2">
                  <h4 className="font-bold text-sm text-gray-900">{persona.name || `Persona ${index + 1}`}</h4>
                  {persona.role && <span className="text-xs bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded font-medium">{persona.role}</span>}
                </div>
                {persona.bio && <p className="text-xs text-gray-600 mb-3">{persona.bio}</p>}
                
                {persona.painPoints && (
                  <div className="mb-2">
                    <p className="text-xs font-semibold text-red-600">Pain Points:</p>
                    <p className="text-xs text-gray-700">{Array.isArray(persona.painPoints) ? persona.painPoints.join(', ') : persona.painPoints}</p>
                  </div>
                )}
                {persona.goals && (
                  <div>
                    <p className="text-xs font-semibold text-green-600">Core Goals:</p>
                    <p className="text-xs text-gray-700">{Array.isArray(persona.goals) ? persona.goals.join(', ') : persona.goals}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* 4. LEAN CANVAS MATRIX */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <Target className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">3. Lean Canvas Strategic Framework</h2>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-3">
          {leanCanvasKeys.map(({ key, label }) => {
            const val = leanCanvas[key];
            return (
              <div key={key} className="print-bp-card">
                <p className="text-xs font-bold text-indigo-600 mb-1">{label}</p>
                <div className="text-xs text-gray-700 leading-normal">
                  {val ? (
                    Array.isArray(val) ? (
                      <ul className="list-disc list-inside space-y-0.5">
                        {val.map((item, idx) => (
                          <li key={idx}>{typeof item === 'string' ? item : JSON.stringify(item)}</li>
                        ))}
                      </ul>
                    ) : (
                      <p>{val}</p>
                    )
                  ) : (
                    <span className="text-gray-400 italic">Not defined</span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* 5. MVP ROADMAP & SPECS */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <Rocket className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">4. MVP Product Roadmap & Technical Scope</h2>
          </div>
          <span className="text-xs bg-yellow-100 text-yellow-800 px-2 py-0.5 rounded font-medium">
            Launch Timeline: {mvpRoadmap.launchTimeline}
          </span>
        </div>

        <div className="print-bp-card mb-4">
          <h3 className="text-xs font-bold text-gray-600 uppercase mb-2">Core MVP Features (Phase 1)</h3>
          {mvpRoadmap.coreFeatures.length > 0 ? (
            <div className="grid grid-cols-2 gap-2">
              {mvpRoadmap.coreFeatures.map((feat, idx) => (
                <div key={idx} className="flex items-start space-x-2 text-xs text-gray-800">
                  <CheckCircle className="w-3.5 h-3.5 text-green-500 mt-0.5 flex-shrink-0" />
                  <span>{typeof feat === 'string' ? feat : (feat.feature || JSON.stringify(feat))}</span>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-xs text-gray-500 italic">No MVP features defined for this plan.</p>
          )}
        </div>

        {mvpRoadmap.technicalRequirements && (
          <div className="print-bp-card">
            <div className="flex items-center space-x-1 mb-1 text-gray-700">
              <Cpu className="w-3.5 h-3.5 text-blue-600" />
              <p className="text-xs font-bold uppercase">Technical Requirements</p>
            </div>
            <p className="text-xs text-gray-700 leading-relaxed">
              {typeof mvpRoadmap.technicalRequirements === 'string'
                ? mvpRoadmap.technicalRequirements
                : JSON.stringify(mvpRoadmap.technicalRequirements)}
            </p>
          </div>
        )}
      </div>

      {/* 6. REVENUE & MONETIZATION */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <DollarSign className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">5. Monetization & Pricing Model</h2>
          </div>
        </div>

        {revenueModel.length > 0 ? (
          <div className="grid grid-cols-2 gap-3">
            {revenueModel.map((item, idx) => (
              <div key={idx} className="print-bp-card">
                <div className="flex justify-between items-center mb-1">
                  <h4 className="font-bold text-xs text-gray-900">{item.model || `Revenue Stream ${idx + 1}`}</h4>
                  {item.projection && (
                    <span className="text-xs font-semibold text-green-600">{item.projection}</span>
                  )}
                </div>
                <p className="text-xs text-gray-600">{item.description}</p>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-xs text-gray-500 italic">No revenue streams generated for this plan.</p>
        )}
      </div>

      {/* 7. COMPETITOR ANALYSIS */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <Shield className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">6. Competitive Landscape & Defensibility</h2>
          </div>
        </div>

        {competitors.length > 0 ? (
          <div className="space-y-2">
            {competitors.map((comp, idx) => (
              <div key={idx} className="print-bp-card">
                <div className="flex justify-between items-baseline mb-1">
                  <h4 className="font-bold text-xs text-gray-900">{comp.name || `Competitor ${idx + 1}`}</h4>
                  <span className="text-xs font-medium text-green-700">
                    Our Advantage: {comp.differentiator || 'Proprietary AI value'}
                  </span>
                </div>
                {comp.description && <p className="text-xs text-gray-600">{comp.description}</p>}
              </div>
            ))}
          </div>
        ) : (
          <p className="text-xs text-gray-500 italic">No competitors generated for this plan.</p>
        )}
      </div>

      {/* 8. NEXT STEPS */}
      <div className="print-bp-section">
        <div className="print-bp-section-header">
          <div className="flex items-center space-x-2">
            <TrendingUp className="w-5 h-5 text-indigo-600" />
            <h2 className="text-xl font-bold text-gray-900">7. Strategic Execution Roadmap</h2>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3">
          {nextSteps.map((item, idx) => (
            <div key={idx} className="print-bp-card">
              <p className="text-xs font-bold text-indigo-600 mb-0.5">{item.step}</p>
              <p className="text-xs text-gray-700">{item.detail}</p>
            </div>
          ))}
        </div>
      </div>

      {/* FOOTER */}
      <div className="print-bp-footer">
        <p>Startup-AI Business Plan • {metadata.startupName} • Page 1 of 1</p>
      </div>
    </div>
  );
};

export default BusinessPlanPrintView;
